---
- name: Working on workstation(ubuntu-c)
  hosts: workstation
  become: yes
  tasks:
    - name: Installing unzip
      package:
        name: unzip
    - name: Installing terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
    

- name: Updating all servers before any installation
  hosts: all
  become: yes
  tasks:
    - name: Updating ubuntu servers
      ansible.builtin.apt:
        update_cache: yes
        only_upgrade: yes
      tags: always
      when: ansible_distribution == "Ubuntu"

    - name: Updating centos servers
      package:
        update_only: yes
        update_cache: yes
      tags: always
      when: ansible_distribution == "Centos"

- name: Ubuntu servers installation
  hosts: ubuntu_servers
  become: yes
  tasks:
    - name: Installing tools into ubuntu servers
      apt:
        name:
          - apache2
          - nginx
        state: present
      when: ansible_distribution == "Ubuntu"
      tags: [ubuntu,apache,apache,nginx]
    - name: Copying file to the servers(Ubuntu)
      copy:
        src: /root/my_ansible_world/assets/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
      tags: [ubuntu,apache,apache,nginx]
- name: Centos servers installation
  hosts: centos_servers
  become: yes
  tasks:
    - name: Installing tools into centos servers
      dnf:
        name:
          - httpd
          - samba
          - mysql
        state: present
      when: ansible_distribution == "Centos"
      tags: [centos,httpd,samba,mysql]
